#!/bin/bash

ip="";
EXIT_NODE_TEST_ADDR=".1.2.3.4.";
TORDNS="ip-port.exitlist.torproject.org";

IFS='.' read -r -a tmpip <<< ${1};
arrip=($tmpip)

for ((i=${#arrip};i>=0;i--)) do
	ip="${ip}${arrip[i]}.";
done

dnsquery_80="${ip}80${EXIT_NODE_TEST_ADDR}${TORDNS}";
dnsquery_443="${ip}443${EXIT_NODE_TEST_ADDR}${TORDNS}";

result_80=$(dig $dnsquery_80 | grep '127.0.0');
result_443=$(dig $dnsquery_443 | grep '127.0.0');

if [ "$result_80" != "" ] || [ "$result_443" != ""] ;then
	echo "TOR EXIT NODE DETECTED FOR HTTP/HTTPS PORT(S).";
else
	echo "Not a known Tor exit node.";
fi
